/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/Settings'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DocIdRouteImport } from './routes/doc/$id'
import { Route as AppTimelineRouteImport } from './routes/app/timeline'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppRulesRouteImport } from './routes/app/rules'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppAccountRouteRouteImport } from './routes/app/account/route'
import { Route as AppAccountIndexRouteImport } from './routes/app/account/index'
import { Route as AppDocIdRouteImport } from './routes/app/doc/$id'
import { Route as AppAccountByokRouteImport } from './routes/app/account/byok'

const SettingsRoute = SettingsRouteImport.update({
  id: '/Settings',
  path: '/Settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppDocIdRoute = AppDocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountByokRoute = AppAccountByokRouteImport.update({
  id: '/byok',
  path: '/byok',
  getParentRoute: () => AppAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/Settings': typeof SettingsRoute
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/rules': typeof AppRulesRoute
  '/app/stats': typeof AppStatsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/doc/$id': typeof DocIdRoute
  '/app/': typeof AppIndexRoute
  '/app/account/byok': typeof AppAccountByokRoute
  '/app/doc/$id': typeof AppDocIdRoute
  '/app/account/': typeof AppAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Settings': typeof SettingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/rules': typeof AppRulesRoute
  '/app/stats': typeof AppStatsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/doc/$id': typeof DocIdRoute
  '/app': typeof AppIndexRoute
  '/app/account/byok': typeof AppAccountByokRoute
  '/app/doc/$id': typeof AppDocIdRoute
  '/app/account': typeof AppAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/Settings': typeof SettingsRoute
  '/app/account': typeof AppAccountRouteRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/rules': typeof AppRulesRoute
  '/app/stats': typeof AppStatsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/doc/$id': typeof DocIdRoute
  '/app/': typeof AppIndexRoute
  '/app/account/byok': typeof AppAccountByokRoute
  '/app/doc/$id': typeof AppDocIdRoute
  '/app/account/': typeof AppAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/Settings'
    | '/app/account'
    | '/app/calendar'
    | '/app/rules'
    | '/app/stats'
    | '/app/timeline'
    | '/doc/$id'
    | '/app/'
    | '/app/account/byok'
    | '/app/doc/$id'
    | '/app/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Settings'
    | '/app/calendar'
    | '/app/rules'
    | '/app/stats'
    | '/app/timeline'
    | '/doc/$id'
    | '/app'
    | '/app/account/byok'
    | '/app/doc/$id'
    | '/app/account'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/Settings'
    | '/app/account'
    | '/app/calendar'
    | '/app/rules'
    | '/app/stats'
    | '/app/timeline'
    | '/doc/$id'
    | '/app/'
    | '/app/account/byok'
    | '/app/doc/$id'
    | '/app/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  DocIdRoute: typeof DocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Settings': {
      id: '/Settings'
      path: '/Settings'
      fullPath: '/Settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/app/doc/$id': {
      id: '/app/doc/$id'
      path: '/doc/$id'
      fullPath: '/app/doc/$id'
      preLoaderRoute: typeof AppDocIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/byok': {
      id: '/app/account/byok'
      path: '/byok'
      fullPath: '/app/account/byok'
      preLoaderRoute: typeof AppAccountByokRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
  }
}

interface AppAccountRouteRouteChildren {
  AppAccountByokRoute: typeof AppAccountByokRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountByokRoute: AppAccountByokRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppRulesRoute: typeof AppRulesRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocIdRoute: typeof AppDocIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppRulesRoute: AppRulesRoute,
  AppStatsRoute: AppStatsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocIdRoute: AppDocIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
  DocIdRoute: DocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
