import type { ClassifiedSentence, PatternType, StylometricProfile } from "../types.ts";

/**
 * Generate a self-contained HTML heatmap report from a StylometricProfile.
 * Single-file HTML with inline CSS/SVG — no external dependencies.
 */
export function generateHtmlReport(profile: StylometricProfile): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prosodeus Analysis Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; background: #0f1117; color: #e0e0e0; padding: 2rem; line-height: 1.6; }
  .container { max-width: 960px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.5rem; color: #fff; }
  h2 { font-size: 1.1rem; margin: 2rem 0 0.75rem; color: #a0a0b0; border-bottom: 1px solid #2a2a3a; padding-bottom: 0.5rem; }
  h3 { font-size: 0.95rem; margin: 1rem 0 0.5rem; color: #8888a0; }
  .subtitle { color: #666; font-size: 0.85rem; margin-bottom: 2rem; }
  .metrics { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 0.75rem; margin-bottom: 1.5rem; }
  .metric { background: #1a1a2e; border: 1px solid #2a2a3e; border-radius: 8px; padding: 0.75rem; }
  .metric-label { font-size: 0.7rem; color: #888; text-transform: uppercase; letter-spacing: 0.05em; }
  .metric-value { font-size: 1.3rem; font-weight: 600; color: #fff; margin-top: 0.25rem; }
  .heatmap { margin: 1rem 0; }
  .sentence { display: inline; padding: 2px 0; cursor: default; border-radius: 2px; }
  .sentence:hover { outline: 1px solid rgba(255,255,255,0.3); }
  .paragraph-break { display: block; height: 0.75rem; }
  .tooltip { position: relative; }
  .tooltip .tip { display: none; position: absolute; bottom: 100%; left: 0; background: #1a1a2e; border: 1px solid #3a3a4e; border-radius: 6px; padding: 0.5rem 0.75rem; font-size: 0.75rem; white-space: nowrap; z-index: 10; }
  .tooltip:hover .tip { display: block; }
  .hot-region { background: #1a1a2e; border: 1px solid #2a2a3e; border-radius: 8px; padding: 1rem; margin: 0.5rem 0; }
  .hot-region-header { display: flex; justify-content: space-between; align-items: center; }
  .heat-badge { background: #ff4444; color: #fff; font-size: 0.7rem; font-weight: 600; padding: 2px 8px; border-radius: 10px; }
  .heat-badge.moderate { background: #ff8800; }
  .heat-badge.mild { background: #ffaa00; color: #000; }
  .pattern-tag { display: inline-block; font-size: 0.7rem; background: #2a2a4e; color: #aaa; padding: 2px 6px; border-radius: 4px; margin: 2px; }
  .violation { display: flex; justify-content: space-between; padding: 0.4rem 0; border-bottom: 1px solid #1a1a2e; font-size: 0.85rem; }
  .violation-dim { color: #ccc; }
  .violation-values { color: #888; }
  .severity-high { color: #ff4444; }
  .severity-medium { color: #ff8800; }
  .severity-low { color: #ffaa00; }
  .chart-container { margin: 1rem 0; }
  svg text { fill: #888; font-family: system-ui, sans-serif; font-size: 11px; }
  svg .axis { stroke: #333; }
  svg .bar { fill: #4a6cf7; }
  svg .bar-hot { fill: #ff4444; }
  svg .line { fill: none; stroke: #4a6cf7; stroke-width: 2; }
  svg .dot { fill: #4a6cf7; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #2a2a3a; font-size: 0.75rem; color: #555; }
</style>
</head>
<body>
<div class="container">
  <h1>Prosodeus Analysis Report</h1>
  <p class="subtitle">${profile.word_count} words | ${profile.sentence_count} sentences | ${profile.paragraph_count} paragraphs</p>

  ${renderMetrics(profile)}

  <h2>Sentence Heatmap</h2>
  ${renderHeatmap(profile.sentences)}

  ${renderHotRegions(profile)}

  <h2>Sentence Length Distribution</h2>
  ${renderLengthChart(profile.sentences)}

  <h2>Heat Distribution</h2>
  ${renderHeatChart(profile.sentences)}

  ${profile.delta ? renderDelta(profile) : ""}

  <footer>Generated by Prosodeus</footer>
</div>
</body>
</html>`;
}

function renderMetrics(profile: StylometricProfile): string {
  const items = [
    { label: "Mean Heat", value: `${profile.mean_heat}/10` },
    { label: "Biber Entropy", value: String(profile.global_biber_entropy) },
    { label: "Device Entropy", value: String(profile.global_device_entropy) },
    { label: "Length Autocorr", value: String(profile.global_sentence_length_autocorrelation) },
    { label: "Convergence", value: String(profile.convergence_slope) },
    { label: "Hot Regions", value: String(profile.hot_regions.length) },
  ];

  return `<div class="metrics">${items
    .map(
      (m) => `
    <div class="metric">
      <div class="metric-label">${m.label}</div>
      <div class="metric-value">${m.value}</div>
    </div>`,
    )
    .join("")}
  </div>`;
}

function heatColor(heat: number): string {
  // 0=cool blue/transparent, 5=orange, 10=red
  if (heat <= 0) return "transparent";
  if (heat <= 2) return `rgba(74, 108, 247, ${heat / 5})`;
  if (heat <= 4) return `rgba(255, 170, 0, ${0.3 + (heat - 2) * 0.15})`;
  if (heat <= 7) return `rgba(255, 136, 0, ${0.5 + (heat - 4) * 0.1})`;
  return `rgba(255, 68, 68, ${0.7 + (heat - 7) * 0.1})`;
}

function renderHeatmap(sentences: ClassifiedSentence[]): string {
  let html = '<div class="heatmap">';
  let currentParagraph = sentences[0]?.paragraph_id ?? 0;

  for (const s of sentences) {
    if (s.paragraph_id !== currentParagraph) {
      html += '<span class="paragraph-break"></span>';
      currentParagraph = s.paragraph_id;
    }

    const patterns = s.classification.patterns.map((p) => p.type).join(", ");
    const title = `Heat: ${s.heat} | ${s.classification.arc_role}${patterns ? " | " + patterns : ""}`;

    html += `<span class="sentence" style="background:${heatColor(s.heat)}" title="${escapeHtml(title)}">${escapeHtml(s.text)} </span>`;
  }

  html += "</div>";
  return html;
}

function renderHotRegions(profile: StylometricProfile): string {
  if (profile.hot_regions.length === 0) return "";

  let html = `<h2>Hot Regions (${profile.hot_regions.length})</h2>`;

  for (const r of profile.hot_regions) {
    const severityClass = r.heat >= 7 ? "" : r.heat >= 5 ? "moderate" : "mild";

    html += `<div class="hot-region">
      <div class="hot-region-header">
        <span>Sentences ${r.start_sentence}–${r.end_sentence}</span>
        <span class="heat-badge ${severityClass}">${r.heat}/10</span>
      </div>
      <p style="font-size:0.85rem;color:#999;margin:0.5rem 0">${escapeHtml(r.description)}</p>
      <div>${r.primary_patterns.map((p) => `<span class="pattern-tag">${formatPatternName(p)}</span>`).join("")}</div>
    </div>`;
  }

  return html;
}

function renderLengthChart(sentences: ClassifiedSentence[]): string {
  if (sentences.length === 0) return "<p>No data</p>";

  const lengths = sentences.map(
    (s) => s.classification.metrics.word_count || s.text.split(/\s+/).length,
  );
  const maxLen = Math.max(...lengths);
  const bins: Record<number, number> = {};
  for (const l of lengths) {
    const bin = Math.floor(l / 5) * 5;
    bins[bin] = (bins[bin] ?? 0) + 1;
  }

  const entries = Object.entries(bins)
    .map(([k, v]) => [Number(k), v] as [number, number])
    .sort((a, b) => a[0] - b[0]);
  const maxCount = Math.max(...entries.map((e) => e[1]));
  const w = 600;
  const h = 200;
  const barW = Math.max(8, Math.floor(w / (entries.length + 1)));
  const padding = 40;

  let bars = "";
  entries.forEach(([bin, count], i) => {
    const x = padding + i * (barW + 2);
    const barH = (count / maxCount) * (h - padding - 20);
    const y = h - padding - barH;
    bars += `<rect class="bar" x="${x}" y="${y}" width="${barW}" height="${barH}" rx="2"/>`;
    if (i % Math.max(1, Math.floor(entries.length / 8)) === 0) {
      bars += `<text x="${x + barW / 2}" y="${h - 10}" text-anchor="middle">${bin}</text>`;
    }
  });

  return `<div class="chart-container">
    <svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
      <line class="axis" x1="${padding}" y1="${h - padding}" x2="${w}" y2="${h - padding}"/>
      ${bars}
      <text x="${w / 2}" y="${h}" text-anchor="middle">Words per sentence (5-word bins)</text>
    </svg>
  </div>`;
}

function renderHeatChart(sentences: ClassifiedSentence[]): string {
  if (sentences.length === 0) return "<p>No data</p>";

  const w = 600;
  const h = 150;
  const padding = 40;
  const usable = w - padding * 2;

  let bars = "";
  sentences.forEach((s, i) => {
    const x = padding + (i / sentences.length) * usable;
    const barW = Math.max(2, usable / sentences.length - 1);
    const barH = (s.heat / 10) * (h - padding - 10);
    const y = h - padding - barH;
    const cls = s.heat >= 3 ? "bar-hot" : "bar";
    bars += `<rect class="${cls}" x="${x}" y="${y}" width="${barW}" height="${barH}" rx="1"/>`;
  });

  return `<div class="chart-container">
    <svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
      <line class="axis" x1="${padding}" y1="${h - padding}" x2="${w}" y2="${h - padding}"/>
      ${bars}
      <text x="${w / 2}" y="${h}" text-anchor="middle">Sentence index</text>
      <text x="10" y="${h / 2}" text-anchor="middle" transform="rotate(-90, 10, ${h / 2})">Heat</text>
    </svg>
  </div>`;
}

function renderDelta(profile: StylometricProfile): string {
  const delta = profile.delta!;

  let html = `<h2>Style Guide: ${escapeHtml(delta.guide)} (distance: ${delta.overall_distance})</h2>`;

  if (delta.violations.length === 0) {
    html += "<p>All targets met.</p>";
    return html;
  }

  html += '<div style="margin:0.5rem 0">';
  for (const v of delta.violations) {
    html += `<div class="violation">
      <span class="violation-dim severity-${v.severity}">${formatDimension(v.dimension)}</span>
      <span class="violation-values">${v.current} (target: ${v.target})</span>
    </div>`;
  }
  html += "</div>";

  return html;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDimension(dim: string): string {
  return dim.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function formatPatternName(p: PatternType): string {
  return p.replace(/_/g, " ");
}
